const STORAGE_KEY = 'edubill_pro_v10_kenya_primary_top_tier';
const ROLE_PRESETS = {
  Administrator:['*'], CEO:['reports_view','finance_manage','finance_post','users_manage'],
  'Finance Officer':['finance_manage','finance_post','reports_view'], Teacher:['students_manage','attendance_manage','exams_manage','reports_view'],
  Bursar:['finance_manage','finance_post','finance_reverse','reports_view'], Cashier:['finance_manage','finance_post'], Custom:[]
};
const PRIVILEGES = [
  ['students_manage','Students'],['attendance_manage','Attendance'],['finance_manage','Finance'],['finance_post','Posting'],['finance_reverse','Reversals'],['exams_manage','Exams'],['staff_manage','Staff'],['reports_view','Reports'],['users_manage','Users'],['settings_manage','Settings']
];
const defaultState = {
  settings:{schoolName:'Rainbow Primary ERP Kenya v10',currentTerm:'Term 1 - Academic Year 2026/2027',schoolPhone:'',schoolEmail:'',schoolAddress:'',currency:'KES',footerNote:'Top-tier colorful Kenya-friendly primary school ERP demo.'},
  auth:{currentUser:null,users:[
    {id:'U1',fullName:'System Administrator',username:'admin',password:'admin123',role:'Administrator',status:'Active',approvalLimit:0,privileges:['*']},
    {id:'U2',fullName:'Chief Executive Officer',username:'ceo',password:'ceo123',role:'CEO',status:'Active',approvalLimit:500000,privileges:ROLE_PRESETS.CEO},
    {id:'U3',fullName:'Finance Officer',username:'finance',password:'finance123',role:'Finance Officer',status:'Active',approvalLimit:150000,privileges:ROLE_PRESETS['Finance Officer']},
    {id:'U4',fullName:'Senior Teacher',username:'teacher',password:'teacher123',role:'Teacher',status:'Active',approvalLimit:0,privileges:ROLE_PRESETS.Teacher}
  ]},
  staff:[], classes:[], feeStructures:[], subjects:[], classSubjects:[], assessments:[], students:[],
  attendance:[], banks:[], invoices:[], payments:[], refunds:[], results:[], activities:[], lastSavedAt:null
};
const state = loadState();
const $ = id => document.getElementById(id);
const els = mapEls();
let promotionLoadedIds = [];
let attendanceLoadedIds = [];
let marksLoadedIds = [];

init();
function mapEls(){
  const ids = ['authScreen','appShell','loginForm','loginUsername','loginPassword','signedInUser','signedInRole','brandSchoolName','brandTerm','pageTitle','pageSubtitle','lastSavedLabel','loadSampleBtn','logoutBtn','backupBtn','importBackupInput','toast','activityList',
  'statStudents','statClasses','statInvoiced','statCollected','statOutstanding','statCredits',
  'classForm','classId','className','classStream','classTeacherId','classStatus','clearClassBtn','classesTableBody',
  'feeForm','feeId','feeClassId','feeName','feeTerm','feeAmount','clearFeeBtn','feesTableBody',
  'subjectForm','subjectId','subjectName','subjectsTableBody','classSubjectForm','mapClassId','mapSubjectId','classSubjectsTableBody','assessmentForm','assessmentId','assessmentName','assessmentOutOf','assessmentsTableBody',
  'studentForm','studentId','admissionNo','studentName','studentClassId','studentClassTeacher','studentFeeHint','studentParent','studentPhone','studentStatus','studentNotes','clearStudentBtn','studentSearch','studentsTableBody','promotionFromClass','promotionToClass','promoLoadBtn','promoSelectAllBtn','promoDeselectAllBtn','promoteSelectedBtn','promotionList',
  'attendanceDate','attendanceClassId','attendanceDefaultStatus','loadAttendanceClassBtn','setAllAttendanceBtn','saveAttendanceBtn','attendanceClassInfo','attendanceTableBody',
  'bankCount','draftInvoiceCount','postedReceiptCount','paidRefundCount','bankForm','bankId','bankName','bankAccountNo','bankBranch','bankStatus','clearBankBtn','banksTableBody','invoiceForm','invoiceId','invoiceDate','invoiceStudentId','invoiceTerm','invoiceAmount','invoiceDescription','clearInvoiceBtn','invoicesTableBody','paymentForm','paymentId','paymentDate','paymentStudentId','paymentInvoiceId','paymentBankId','paymentMethod','paymentAmount','clearPaymentBtn','paymentsTableBody','refundForm','refundId','refundDate','refundStudentId','refundCreditHint','refundBankId','refundAmount','refundReason','clearRefundBtn','refundsTableBody','ledgerStudentId','loadLedgerBtn','ledgerTableBody',
  'examDate','examClassId','examAssessmentId','examSubjectId','loadExamClassBtn','saveMarksBtn','examInfo','marksTableBody','resultsTableBody',
  'staffForm','staffId','staffNo','staffName','staffRole','staffDepartment','staffPhone','staffStatus','clearStaffBtn','staffSearch','staffTableBody',
  'reportBalance','reportPerformance','reportAttendance','reportMessages','reportBalancesTableBody','reportInsightList','reportForm','reportType','reportClassId','reportStudentId','reportTerm','reportFromDate','reportToDate','runReportBtn','printReportBtn','exportCsvBtn','exportExcelBtn','exportJsonBtn','reportPreviewTitle','reportPreviewMeta','reportPreviewHead','reportPreviewBody','insightBalances','insightCredits','insightInvoices','insightReceipts','autoInvoiceBtn','todayReceiptsBtn',
  'userForm','userId','userFullName','userUsername','userPassword','userRole','userStatus','approvalLimit','userPrivilegesGrid','clearUserBtn','userSearch','usersTableBody',
  'settingsForm','schoolName','currentTerm','schoolPhone','schoolEmail','schoolAddress','currency','footerNote','menuToggle','mobileMenuBtn'];
  const out = {}; ids.forEach(id=> out[id]=$(id)); out.navLinks=document.querySelectorAll('.nav-link'); out.sections=document.querySelectorAll('.section'); out.quickActions=document.querySelectorAll('.quick-action'); out.sidebar=document.getElementById('sidebar'); out.mobileNav=document.querySelector('.mobile-bottom-nav'); return out;
}
function init(){ bindEvents(); fillStaticRoleOptions(); renderPrivilegeMatrix(); setToday(); syncAuthUI(); if(els.reportTerm && !els.reportTerm.value) els.reportTerm.value='Term 1'; renderAll(); }
function bindEvents(){
  els.loginForm.addEventListener('submit', onLogin); els.logoutBtn.addEventListener('click', logout); if(els.menuToggle) els.menuToggle.addEventListener('click', toggleSidebar); if(els.mobileMenuBtn) els.mobileMenuBtn.addEventListener('click', toggleSidebar);
  els.navLinks.forEach(b=>b.addEventListener('click',()=>switchSection(b.dataset.section))); window.addEventListener('resize', closeSidebarOnDesktop); els.quickActions.forEach(b=>b.addEventListener('click',()=>switchSection(b.dataset.jump)));
  els.loadSampleBtn.addEventListener('click', loadSampleData); els.backupBtn.addEventListener('click', exportBackup); els.importBackupInput.addEventListener('change', importBackup);
  if(els.autoInvoiceBtn) els.autoInvoiceBtn.addEventListener('click', autoGenerateClassInvoices); if(els.todayReceiptsBtn) els.todayReceiptsBtn.addEventListener('click', showTodayReceipts);
  if(els.runReportBtn) els.runReportBtn.addEventListener('click', runReport); if(els.printReportBtn) els.printReportBtn.addEventListener('click', printCurrentReport); if(els.exportCsvBtn) els.exportCsvBtn.addEventListener('click', ()=>exportCurrentReport('csv')); if(els.exportExcelBtn) els.exportExcelBtn.addEventListener('click', ()=>exportCurrentReport('excel')); if(els.exportJsonBtn) els.exportJsonBtn.addEventListener('click', ()=>exportCurrentReport('json'));
  els.classForm.addEventListener('submit', saveClass); els.clearClassBtn.addEventListener('click', ()=>clearForm('class'));
  els.feeForm.addEventListener('submit', saveFee); els.clearFeeBtn.addEventListener('click', ()=>clearForm('fee'));
  els.subjectForm.addEventListener('submit', saveSubject); els.classSubjectForm.addEventListener('submit', saveClassSubject); els.assessmentForm.addEventListener('submit', saveAssessment);
  els.staffForm.addEventListener('submit', saveStaff); els.clearStaffBtn.addEventListener('click', ()=>clearForm('staff')); els.staffSearch.addEventListener('input', renderStaff);
  els.studentForm.addEventListener('submit', saveStudent); els.clearStudentBtn.addEventListener('click', ()=>clearForm('student')); els.studentSearch.addEventListener('input', renderStudents); els.studentClassId.addEventListener('change', updateStudentClassHints);
  els.promoLoadBtn.addEventListener('click', loadPromotionStudents); els.promoSelectAllBtn.addEventListener('click', ()=>setPromotionChecks(true)); els.promoDeselectAllBtn.addEventListener('click', ()=>setPromotionChecks(false)); els.promoteSelectedBtn.addEventListener('click', promoteSelected);
  els.loadAttendanceClassBtn.addEventListener('click', loadAttendanceClass); els.setAllAttendanceBtn.addEventListener('click', applyDefaultAttendance); els.saveAttendanceBtn.addEventListener('click', saveAttendanceBatch);
  els.bankForm.addEventListener('submit', saveBank); els.clearBankBtn.addEventListener('click', ()=>clearForm('bank'));
  els.invoiceForm.addEventListener('submit', saveInvoice); els.clearInvoiceBtn.addEventListener('click', ()=>clearForm('invoice')); els.invoiceStudentId.addEventListener('change', invoiceStudentChanged);
  els.paymentForm.addEventListener('submit', saveReceipt); els.clearPaymentBtn.addEventListener('click', ()=>clearForm('payment')); els.paymentStudentId.addEventListener('change', populateOpenInvoices);
  els.refundForm.addEventListener('submit', saveRefund); els.clearRefundBtn.addEventListener('click', ()=>clearForm('refund')); els.refundStudentId.addEventListener('change', updateRefundCreditHint);
  els.loadLedgerBtn.addEventListener('click', renderLedger);
  els.loadExamClassBtn.addEventListener('click', loadMarksClass); els.saveMarksBtn.addEventListener('click', saveMarksBatch); els.examClassId.addEventListener('change', populateExamSubjects);
  els.userForm.addEventListener('submit', saveUser); els.clearUserBtn.addEventListener('click', ()=>clearForm('user')); els.userSearch.addEventListener('input', renderUsers); els.userRole.addEventListener('change', onRoleChange);
  els.settingsForm.addEventListener('submit', saveSettings);
}

function loadState(){ try{ const raw = localStorage.getItem(STORAGE_KEY); return raw?mergeDefault(JSON.parse(raw), structuredClone(defaultState)):structuredClone(defaultState);}catch{return structuredClone(defaultState);} }
function mergeDefault(saved, def){ for(const k in def){ if(saved[k]===undefined) saved[k]=def[k]; else if(def[k] && typeof def[k]==='object' && !Array.isArray(def[k])) saved[k]=mergeDefault(saved[k], def[k]); } return saved; }
function persist(msg='Saved'){ state.lastSavedAt=new Date().toISOString(); localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); els.lastSavedLabel.textContent=formatDateTime(state.lastSavedAt); if(msg) toast(msg); }
function uid(p='ID'){ return `${p}_${Math.random().toString(36).slice(2,7)}${Date.now().toString().slice(-4)}`; }
function currentUser(){ return state.auth.currentUser; }
function hasPrivilege(key){ const user=currentUser(); return !!user && (user.privileges.includes('*') || user.privileges.includes(key)); }
function requirePrivilege(key,msg){ if(hasPrivilege(key)) return true; toast(msg || 'Access denied'); return false; }
function money(v){ return `${state.settings.currency||'KES'} ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`; }
function escapeHtml(v=''){ return String(v).replace(/[&<>"']/g, s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s])); }
function formatDate(d){ if(!d) return ''; return new Date(d).toLocaleDateString(); }
function formatDateTime(d){ if(!d) return 'Never'; return new Date(d).toLocaleString(); }
function toast(msg){ els.toast.textContent=msg; els.toast.classList.remove('hidden'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>els.toast.classList.add('hidden'),2600); }
function logActivity(title, detail=''){ state.activities.unshift({id:uid('ACT'),time:new Date().toISOString(),title,detail}); state.activities=state.activities.slice(0,20); }
function setToday(){ const today=new Date().toISOString().slice(0,10); ['attendanceDate','invoiceDate','paymentDate','refundDate','examDate'].forEach(id=>{ if(els[id]) els[id].value=today; }); }
function switchSection(id){ els.navLinks.forEach(b=>b.classList.toggle('active', b.dataset.section===id)); els.sections.forEach(s=>s.classList.toggle('active', s.id===id)); if(window.innerWidth<=900 && els.sidebar) els.sidebar.classList.remove('open'); els.pageTitle.textContent = document.querySelector(`.nav-link[data-section="${id}"]`).textContent.replace(/^[^A-Za-z]+\s*/,''); const subtitleMap={setup:'Configure classes, fees, subjects, and assessments.',students:'Manage student records and promotions.',attendance:'Mark attendance by class.',finance:'Invoices, receipts, refunds, and ledgers.',exams:'Marks entry by class, subject, and assessment.',staff:'Manage staff and teachers.',reports:'View balances, performance, and attendance.',users:'Access control and approvals.',settings:'Institution settings.'}; els.pageSubtitle.textContent=subtitleMap[id]||'A user-friendly school system.'; }
function syncAuthUI(){ const user=currentUser(); const logged=!!user; els.authScreen.classList.toggle('hidden', logged); els.appShell.classList.toggle('hidden', !logged); if(logged){ els.signedInUser.textContent=user.fullName; els.signedInRole.textContent=user.role; } els.brandSchoolName.textContent=state.settings.schoolName; els.brandTerm.textContent=state.settings.currentTerm; els.lastSavedLabel.textContent=formatDateTime(state.lastSavedAt); }
function onLogin(e){ e.preventDefault(); const user=state.auth.users.find(u=>u.username===els.loginUsername.value.trim() && u.password===els.loginPassword.value && u.status==='Active'); if(!user) return toast('Invalid username or password'); state.auth.currentUser={id:user.id,fullName:user.fullName,username:user.username,role:user.role,privileges:user.privileges}; persist('Login successful'); syncAuthUI(); renderAll(); }
function logout(){ state.auth.currentUser=null; persist('Logged out'); syncAuthUI(); }
function toggleSidebar(){ if(!els.sidebar) return; els.sidebar.classList.toggle('open'); }
function closeSidebarOnDesktop(){ if(window.innerWidth>900 && els.sidebar) els.sidebar.classList.remove('open'); }


function renderAll(){ renderSelectOptions(); renderDashboard(); renderActivities(); renderClasses(); renderFees(); renderSubjects(); renderAssessments(); renderStaff(); renderStudents(); renderFinance(); renderResults(); renderReports(); renderUsers(); renderSettings(); }
function renderActivities(){ els.activityList.innerHTML = state.activities.length ? state.activities.map(a=>`<div class="list-item"><strong>${escapeHtml(a.title)}</strong><div class="muted">${escapeHtml(a.detail)} · ${formatDateTime(a.time)}</div></div>`).join('') : 'No activity yet.'; }
function renderDashboard(){
  els.statStudents.textContent = state.students.length; els.statClasses.textContent = activeClasses().length; els.statInvoiced.textContent = money(sum(state.invoices.filter(x=>x.status==='Posted').map(x=>x.amount))); els.statCollected.textContent = money(sum(state.payments.filter(x=>x.status==='Posted').map(x=>x.amount))); els.statOutstanding.textContent = money(sum(state.students.map(s=>studentOutstanding(s.id)))); els.statCredits.textContent = money(sum(state.students.map(s=>studentCredit(s.id))));
}
function activeClasses(){ return state.classes.filter(c=>c.status==='Active'); }
function classLabel(id){ const c=state.classes.find(x=>x.id===id); return c?`${c.name}${c.stream?` ${c.stream}`:''}`:''; }
function teacherName(id){ const t=state.staff.find(x=>x.id===id); return t?t.name:''; }
function studentName(id){ const s=state.students.find(x=>x.id===id); return s?s.name:''; }
function bankName(id){ const b=state.banks.find(x=>x.id===id); return b?b.name:''; }
function subjectName(id){ const s=state.subjects.find(x=>x.id===id); return s?s.name:''; }
function assessmentName(id){ const a=state.assessments.find(x=>x.id===id); return a?a.name:''; }
function assessmentOutOf(id){ const a=state.assessments.find(x=>x.id===id); return a?Number(a.outOf):100; }
function sum(arr){ return arr.reduce((a,b)=>a+Number(b||0),0); }
function gradeFromPercent(p){ return p>=80?'A':p>=70?'B':p>=60?'C':p>=50?'D':'E'; }
function statusBadge(s){ const cls = ['Posted','Paid','Active','Approved','Present'].includes(s)?'success':(['Draft','Late'].includes(s)?'warn':'danger'); return `<span class="badge ${cls}">${escapeHtml(s)}</span>`; }

function renderSelectOptions(){
  fillSelect(els.classTeacherId, [{id:'',label:'Select teacher'}].concat(state.staff.map(s=>({id:s.id,label:`${s.name} (${s.role})`}))));
  const classOpts=[{id:'',label:'All / Select class'}].concat(activeClasses().map(c=>({id:c.id,label:classLabel(c.id)})));
  ['feeClassId','mapClassId','studentClassId','promotionFromClass','promotionToClass','attendanceClassId','examClassId','reportClassId'].forEach(id=>fillSelect(els[id], classOpts));
  const students=[{id:'',label:'All / Select student'}].concat(state.students.map(s=>({id:s.id,label:`${s.admissionNo} - ${s.name}`})));
  ['invoiceStudentId','paymentStudentId','refundStudentId','ledgerStudentId','reportStudentId'].forEach(id=>fillSelect(els[id], students));
  const banks=[{id:'',label:'Select bank'}].concat(state.banks.filter(b=>b.status==='Active').map(b=>({id:b.id,label:b.name}))); ['paymentBankId','refundBankId'].forEach(id=>fillSelect(els[id], banks));
  fillSelect(els.mapSubjectId, [{id:'',label:'Select subject'}].concat(state.subjects.map(s=>({id:s.id,label:s.name}))));
  fillSelect(els.examAssessmentId, [{id:'',label:'Select assessment'}].concat(state.assessments.map(a=>({id:a.id,label:`${a.name} (/${a.outOf})`}))))
  populateExamSubjects(); populateOpenInvoices(); updateRefundCreditHint(); updateStudentClassHints();
}
function fillSelect(el, arr){ if(!el) return; const current=el.value; el.innerHTML=arr.map(o=>`<option value="${o.id}">${escapeHtml(o.label)}</option>`).join(''); if(arr.some(o=>String(o.id)===String(current))) el.value=current; }

function saveClass(e){ e.preventDefault(); if(!requirePrivilege('settings_manage','No access to setup classes')) return; const id=els.classId.value||uid('CLS'); const rec={id,name:els.className.value.trim(),stream:els.classStream.value.trim(),teacherId:els.classTeacherId.value,status:els.classStatus.value}; upsert(state.classes, rec); clearForm('class'); logActivity('Class saved', classLabel(id)||rec.name); persist('Class saved'); renderAll(); }
function renderClasses(){ els.classesTableBody.innerHTML = state.classes.length?state.classes.map(c=>`<tr><td>${escapeHtml(classLabel(c.id))}</td><td>${escapeHtml(teacherName(c.teacherId)||'-')}</td><td>${statusBadge(c.status)}</td><td><button class="table-btn" onclick="editClass('${c.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="4" class="muted">No classes yet.</td></tr>`; }
window.editClass=id=>{ const c=findById(state.classes,id); if(!c) return; els.classId.value=c.id; els.className.value=c.name; els.classStream.value=c.stream||''; els.classTeacherId.value=c.teacherId||''; els.classStatus.value=c.status; switchSection('setup'); };

function saveFee(e){ e.preventDefault(); if(!requirePrivilege('settings_manage','No access to fee setup')) return; const id=els.feeId.value||uid('FEE'); const rec={id,classId:els.feeClassId.value,name:els.feeName.value.trim(),term:els.feeTerm.value.trim(),amount:Number(els.feeAmount.value)}; if(!rec.classId) return toast('Select class'); upsert(state.feeStructures, rec); clearForm('fee'); logActivity('Fee setup saved', `${rec.name} for ${classLabel(rec.classId)}`); persist('Fee setup saved'); renderAll(); }
function renderFees(){ els.feesTableBody.innerHTML = state.feeStructures.length?state.feeStructures.map(f=>`<tr><td>${escapeHtml(classLabel(f.classId))}</td><td>${escapeHtml(f.name)}</td><td>${escapeHtml(f.term)}</td><td>${money(f.amount)}</td><td><button class="table-btn" onclick="editFee('${f.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="5" class="muted">No fee setup yet.</td></tr>`; }
window.editFee=id=>{ const f=findById(state.feeStructures,id); if(!f) return; els.feeId.value=f.id; els.feeClassId.value=f.classId; els.feeName.value=f.name; els.feeTerm.value=f.term; els.feeAmount.value=f.amount; switchSection('setup'); };

function saveSubject(e){ e.preventDefault(); if(!requirePrivilege('settings_manage')) return; const id=els.subjectId.value||uid('SUB'); upsert(state.subjects,{id,name:els.subjectName.value.trim()}); clearForm('subject'); persist('Subject saved'); renderAll(); }
function renderSubjects(){ els.subjectsTableBody.innerHTML = state.subjects.length?state.subjects.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td><button class="table-btn" onclick="editSubject('${s.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="2" class="muted">No subjects yet.</td></tr>`; els.classSubjectsTableBody.innerHTML = state.classSubjects.length?state.classSubjects.map(m=>`<tr><td>${escapeHtml(classLabel(m.classId))}</td><td>${escapeHtml(subjectName(m.subjectId))}</td><td><button class="table-btn danger" onclick="removeClassSubject('${m.id}')">Remove</button></td></tr>`).join(''):`<tr><td colspan="3" class="muted">No mappings yet.</td></tr>`; }
window.editSubject=id=>{ const s=findById(state.subjects,id); els.subjectId.value=s.id; els.subjectName.value=s.name; switchSection('setup'); };
window.removeClassSubject=id=>{ state.classSubjects = state.classSubjects.filter(x=>x.id!==id); persist('Mapping removed'); renderAll(); };
function saveClassSubject(e){ e.preventDefault(); if(!requirePrivilege('settings_manage')) return; const classId=els.mapClassId.value, subjectId=els.mapSubjectId.value; if(!classId||!subjectId) return toast('Select class and subject'); if(state.classSubjects.some(x=>x.classId===classId && x.subjectId===subjectId)) return toast('Mapping already exists'); state.classSubjects.push({id:uid('MAP'),classId,subjectId}); persist('Class subject added'); renderAll(); }
function saveAssessment(e){ e.preventDefault(); if(!requirePrivilege('settings_manage')) return; const id=els.assessmentId.value||uid('ASM'); upsert(state.assessments,{id,name:els.assessmentName.value.trim(),outOf:Number(els.assessmentOutOf.value)}); clearForm('assessment'); persist('Assessment saved'); renderAll(); }
function renderAssessments(){ els.assessmentsTableBody.innerHTML = state.assessments.length?state.assessments.map(a=>`<tr><td>${escapeHtml(a.name)}</td><td>${a.outOf}</td><td><button class="table-btn" onclick="editAssessment('${a.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="3" class="muted">No assessments yet.</td></tr>`; }
window.editAssessment=id=>{ const a=findById(state.assessments,id); els.assessmentId.value=a.id; els.assessmentName.value=a.name; els.assessmentOutOf.value=a.outOf; switchSection('setup'); };

function saveStaff(e){ e.preventDefault(); if(!requirePrivilege('staff_manage','No access to staff')) return; const id=els.staffId.value||uid('STF'); const rec={id,staffNo:els.staffNo.value.trim(),name:els.staffName.value.trim(),role:els.staffRole.value.trim(),department:els.staffDepartment.value.trim(),phone:els.staffPhone.value.trim(),status:els.staffStatus.value}; upsert(state.staff,rec); clearForm('staff'); logActivity('Staff saved', rec.name); persist('Staff saved'); renderAll(); }
function renderStaff(){ const q=els.staffSearch.value?.toLowerCase()||''; const rows=state.staff.filter(s=>!q||Object.values(s).join(' ').toLowerCase().includes(q)); els.staffTableBody.innerHTML=rows.length?rows.map(s=>`<tr><td>${escapeHtml(s.staffNo)}</td><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.role)}</td><td>${escapeHtml(s.department||'-')}</td><td>${statusBadge(s.status)}</td><td><button class="table-btn" onclick="editStaff('${s.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="6" class="muted">No staff yet.</td></tr>`; }
window.editStaff=id=>{ const s=findById(state.staff,id); Object.assign(els,{}) ; els.staffId.value=s.id; els.staffNo.value=s.staffNo; els.staffName.value=s.name; els.staffRole.value=s.role; els.staffDepartment.value=s.department||''; els.staffPhone.value=s.phone||''; els.staffStatus.value=s.status; switchSection('staff'); };

function updateStudentClassHints(){ const classId=els.studentClassId.value; const cls=findById(state.classes,classId); els.studentClassTeacher.value=cls?teacherName(cls.teacherId)||'No teacher linked':''; const fee=state.feeStructures.find(f=>f.classId===classId); els.studentFeeHint.value=fee?`${fee.name} - ${money(fee.amount)} (${fee.term})`:'No fee setup linked'; }
function saveStudent(e){ e.preventDefault(); if(!requirePrivilege('students_manage','No access to students')) return; const id=els.studentId.value||uid('STD'); const rec={id,admissionNo:els.admissionNo.value.trim(),name:els.studentName.value.trim(),classId:els.studentClassId.value,parent:els.studentParent.value.trim(),phone:els.studentPhone.value.trim(),status:els.studentStatus.value,notes:els.studentNotes.value.trim()}; if(!rec.classId) return toast('Select class'); upsert(state.students, rec); clearForm('student'); logActivity('Student saved', rec.name); persist('Student saved'); renderAll(); }
function renderStudents(){ const q=els.studentSearch.value?.toLowerCase()||''; const rows=state.students.filter(s=>!q||Object.values(s).join(' ').toLowerCase().includes(q)); els.studentsTableBody.innerHTML = rows.length?rows.map(s=>{const cls=findById(state.classes,s.classId); return `<tr><td>${escapeHtml(s.admissionNo)}</td><td>${escapeHtml(s.name)}</td><td>${escapeHtml(classLabel(s.classId))}</td><td>${escapeHtml(teacherName(cls?.teacherId)||'-')}</td><td>${money(studentOutstanding(s.id))}</td><td>${money(studentCredit(s.id))}</td><td><button class="table-btn" onclick="editStudent('${s.id}')">Edit</button></td></tr>`;}).join(''):`<tr><td colspan="7" class="muted">No students yet.</td></tr>`; }
window.editStudent=id=>{ const s=findById(state.students,id); els.studentId.value=s.id; els.admissionNo.value=s.admissionNo; els.studentName.value=s.name; els.studentClassId.value=s.classId; els.studentParent.value=s.parent||''; els.studentPhone.value=s.phone||''; els.studentStatus.value=s.status; els.studentNotes.value=s.notes||''; updateStudentClassHints(); switchSection('students'); };
function loadPromotionStudents(){ const from=els.promotionFromClass.value; const rows=state.students.filter(s=>s.classId===from && s.status==='Active'); promotionLoadedIds = rows.map(r=>r.id); els.promotionList.innerHTML = rows.length?rows.map(s=>`<label class="promotion-row"><input type="checkbox" class="promo-check" value="${s.id}" checked><span>${escapeHtml(s.admissionNo)}</span><strong>${escapeHtml(s.name)}</strong></label>`).join(''):'<div class="empty">No active students in selected class.</div>'; }
function setPromotionChecks(v){ document.querySelectorAll('.promo-check').forEach(c=>c.checked=v); }
function promoteSelected(){ if(!requirePrivilege('students_manage')) return; const to=els.promotionToClass.value; const selected=[...document.querySelectorAll('.promo-check:checked')].map(c=>c.value); if(!to||!selected.length) return toast('Select target class and at least one student'); selected.forEach(id=>{ const s=findById(state.students,id); if(s) s.classId=to; }); logActivity('Students promoted', `${selected.length} students moved to ${classLabel(to)}`); persist('Students promoted'); renderAll(); loadPromotionStudents(); }

function loadAttendanceClass(){ const classId=els.attendanceClassId.value; const rows=state.students.filter(s=>s.classId===classId && s.status==='Active'); attendanceLoadedIds = rows.map(r=>r.id); const cls=findById(state.classes,classId); els.attendanceClassInfo.textContent = cls?`Class: ${classLabel(classId)} | Teacher: ${teacherName(cls.teacherId)||'Not linked'} | Students loaded: ${rows.length}`:'Choose a class'; els.attendanceTableBody.innerHTML = rows.length?rows.map(s=>{ const existing=state.attendance.find(a=>a.date===els.attendanceDate.value && a.studentId===s.id); return `<tr><td>${escapeHtml(s.admissionNo)}</td><td>${escapeHtml(s.name)}</td><td><select class="att-status" data-id="${s.id}"><option ${optSel(existing?.status,'Present')}>Present</option><option ${optSel(existing?.status,'Absent')}>Absent</option><option ${optSel(existing?.status,'Late')}>Late</option></select></td><td><input class="att-remarks" data-id="${s.id}" value="${escapeHtml(existing?.remarks||'')}"></td></tr>`; }).join(''):`<tr><td colspan="4" class="muted">No students in class.</td></tr>`; }
function applyDefaultAttendance(){ const v=els.attendanceDefaultStatus.value; document.querySelectorAll('.att-status').forEach(s=>s.value=v); }
function saveAttendanceBatch(){ if(!requirePrivilege('attendance_manage')) return; const date=els.attendanceDate.value; if(!attendanceLoadedIds.length) return toast('Load a class first'); attendanceLoadedIds.forEach(id=>{ const status=document.querySelector(`.att-status[data-id="${id}"]`)?.value; const remarks=document.querySelector(`.att-remarks[data-id="${id}"]`)?.value||''; const existing=state.attendance.find(a=>a.date===date && a.studentId===id); const rec={id:existing?.id||uid('ATT'),date,studentId:id,classId:findById(state.students,id)?.classId,status,remarks}; upsert(state.attendance,rec); }); logActivity('Attendance saved', `${attendanceLoadedIds.length} records for ${formatDate(date)}`); persist('Attendance saved'); renderAll(); }

function saveBank(e){ e.preventDefault(); if(!requirePrivilege('finance_manage')) return; const id=els.bankId.value||uid('BNK'); upsert(state.banks,{id,name:els.bankName.value.trim(),accountNo:els.bankAccountNo.value.trim(),branch:els.bankBranch.value.trim(),status:els.bankStatus.value}); clearForm('bank'); persist('Bank saved'); renderAll(); }
function renderFinance(){
  els.bankCount.textContent=state.banks.length; els.draftInvoiceCount.textContent=state.invoices.filter(x=>x.status==='Draft').length; els.postedReceiptCount.textContent=state.payments.filter(x=>x.status==='Posted').length; els.paidRefundCount.textContent=state.refunds.filter(x=>x.status==='Paid').length;
  els.banksTableBody.innerHTML=state.banks.length?state.banks.map(b=>`<tr><td>${escapeHtml(b.name)}</td><td>${escapeHtml(b.accountNo||'-')}</td><td>${escapeHtml(b.branch||'-')}</td><td>${money(bankBalance(b.id))}</td><td><button class="table-btn" onclick="editBank('${b.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="5" class="muted">No banks yet.</td></tr>`;
  els.invoicesTableBody.innerHTML=state.invoices.length?state.invoices.slice().reverse().map(i=>`<tr><td>${escapeHtml(i.number)}</td><td>${formatDate(i.date)}</td><td>${escapeHtml(studentName(i.studentId))}</td><td>${money(i.amount)}</td><td>${statusBadge(i.status)}</td><td>${invoiceActionHtml(i)}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">No invoices yet.</td></tr>`;
  els.paymentsTableBody.innerHTML=state.payments.length?state.payments.slice().reverse().map(p=>`<tr><td>${escapeHtml(p.number)}</td><td>${formatDate(p.date)}</td><td>${escapeHtml(studentName(p.studentId))}</td><td>${money(p.amount)}</td><td>${statusBadge(p.status)}</td><td>${receiptActionHtml(p)}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">No receipts yet.</td></tr>`;
  els.refundsTableBody.innerHTML=state.refunds.length?state.refunds.slice().reverse().map(r=>`<tr><td>${escapeHtml(r.number)}</td><td>${formatDate(r.date)}</td><td>${escapeHtml(studentName(r.studentId))}</td><td>${money(r.amount)}</td><td>${statusBadge(r.status)}</td><td>${refundActionHtml(r)}</td></tr>`).join(''):`<tr><td colspan="6" class="muted">No refunds yet.</td></tr>`;
  renderLedger();
}
function invoiceStudentChanged(){ const studentId=els.invoiceStudentId.value; const stu=findById(state.students,studentId); const fee=state.feeStructures.find(f=>f.classId===stu?.classId); if(fee){ if(!els.invoiceAmount.value) els.invoiceAmount.value=fee.amount; if(!els.invoiceDescription.value) els.invoiceDescription.value=`${fee.name} - ${classLabel(fee.classId)}`; if(!els.invoiceTerm.value) els.invoiceTerm.value=fee.term; } }
function saveInvoice(e){ e.preventDefault(); if(!requirePrivilege('finance_manage')) return; const studentId=els.invoiceStudentId.value; if(!studentId) return toast('Select student'); const stu=findById(state.students,studentId); const fee=state.feeStructures.find(f=>f.classId===stu?.classId); const id=els.invoiceId.value||uid('INV'); upsert(state.invoices,{id,number:findById(state.invoices,id)?.number||autoNo('INV',state.invoices.length+1),date:els.invoiceDate.value,studentId,term:els.invoiceTerm.value,amount:Number(els.invoiceAmount.value||(fee?.amount||0)),description:els.invoiceDescription.value.trim()||(fee?`${fee.name} - ${classLabel(fee.classId)}`:'School fees'),status:findById(state.invoices,id)?.status||'Draft'}); clearForm('invoice'); logActivity('Invoice saved','Draft invoice prepared'); persist('Invoice saved'); renderAll(); }
window.postInvoice=id=>{ if(!requirePrivilege('finance_post')) return; const i=findById(state.invoices,id); if(!i||i.status!=='Draft') return; i.status='Posted'; logActivity('Invoice posted', `${i.number} posted`); persist('Invoice posted'); renderAll(); };
window.reverseInvoice=id=>{ if(!requirePrivilege('finance_reverse')) return; const i=findById(state.invoices,id); if(!i||i.status!=='Posted') return; if(receiptsAgainstInvoice(id)>0) return toast('Reverse related receipts first'); i.status='Reversed'; persist('Invoice reversed'); renderAll(); };
function saveReceipt(e){ e.preventDefault(); if(!requirePrivilege('finance_manage')) return; const invoiceId=els.paymentInvoiceId.value; const amount=Number(els.paymentAmount.value); if(amount>invoiceOpenBalance(invoiceId)) return toast('Receipt exceeds invoice balance'); const id=els.paymentId.value||uid('RCT'); upsert(state.payments,{id,number:findById(state.payments,id)?.number||autoNo('RCT',state.payments.length+1),date:els.paymentDate.value,studentId:els.paymentStudentId.value,invoiceId,bankId:els.paymentBankId.value,method:els.paymentMethod.value,amount,status:findById(state.payments,id)?.status||'Draft'}); clearForm('payment'); persist('Receipt saved'); renderAll(); }
window.postReceipt=id=>{ if(!requirePrivilege('finance_post')) return; const p=findById(state.payments,id); if(!p||p.status!=='Draft') return; if(p.amount>invoiceOpenBalance(p.invoiceId)) return toast('Receipt exceeds invoice balance'); p.status='Posted'; persist('Receipt posted'); renderAll(); };
window.reverseReceipt=id=>{ if(!requirePrivilege('finance_reverse')) return; const p=findById(state.payments,id); if(!p||p.status!=='Posted') return; p.status='Reversed'; persist('Receipt reversed'); renderAll(); };
function updateRefundCreditHint(){ const sid=els.refundStudentId.value; els.refundCreditHint.value = money(studentCredit(sid)); }
function saveRefund(e){ e.preventDefault(); if(!requirePrivilege('finance_manage')) return; const sid=els.refundStudentId.value; const amount=Number(els.refundAmount.value); const credit=studentCredit(sid); if(amount>credit) return toast(`Refund blocked. Available credit is only ${money(credit)}`); const id=els.refundId.value||uid('RFD'); upsert(state.refunds,{id,number:findById(state.refunds,id)?.number||autoNo('RFD',state.refunds.length+1),date:els.refundDate.value,studentId:sid,bankId:els.refundBankId.value,amount,reason:els.refundReason.value.trim(),status:findById(state.refunds,id)?.status||'Draft'}); clearForm('refund'); persist('Refund saved'); renderAll(); }
window.approveRefund=id=>{ if(!requirePrivilege('finance_post')) return; const r=findById(state.refunds,id); if(!r||r.status!=='Draft') return; if(r.amount>studentCredit(r.studentId)) return toast('Credit no longer sufficient'); r.status='Approved'; persist('Refund approved'); renderAll(); };
window.payRefund=id=>{ if(!requirePrivilege('finance_post')) return; const r=findById(state.refunds,id); if(!r||r.status!=='Approved') return; if(r.amount>studentCredit(r.studentId)) return toast('Refund exceeds available credit'); if(r.amount>bankBalance(r.bankId)) return toast('Bank balance too low'); r.status='Paid'; persist('Refund paid'); renderAll(); };
window.reverseRefund=id=>{ if(!requirePrivilege('finance_reverse')) return; const r=findById(state.refunds,id); if(!r||r.status!=='Paid') return; r.status='Reversed'; persist('Refund reversed'); renderAll(); };
function populateOpenInvoices(){ const sid=els.paymentStudentId.value; fillSelect(els.paymentInvoiceId,[{id:'',label:'Select invoice'}].concat(state.invoices.filter(i=>i.studentId===sid&&i.status==='Posted'&&invoiceOpenBalance(i.id)>0).map(i=>({id:i.id,label:`${i.number} - ${money(invoiceOpenBalance(i.id))}`})))); }
function renderLedger(){ const sid=els.ledgerStudentId.value||state.students[0]?.id||''; if(els.ledgerStudentId.value!==sid && sid) els.ledgerStudentId.value=sid; const rows=studentLedgerRows(sid); let bal=0; els.ledgerTableBody.innerHTML = rows.length?rows.map(r=>{ bal += Number(r.debit||0)-Number(r.credit||0); return `<tr><td>${formatDate(r.date)}</td><td>${escapeHtml(r.ref)}</td><td>${escapeHtml(r.type)}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td><td>${money(bal)}</td><td>${escapeHtml(r.narration)}</td></tr>`; }).join(''):`<tr><td colspan="7" class="muted">No ledger entries.</td></tr>`; }
function studentLedgerRows(sid){ if(!sid) return []; const rows=[]; state.invoices.filter(i=>i.studentId===sid&&i.status==='Posted').forEach(i=>rows.push({date:i.date,ref:i.number,type:'Invoice',debit:i.amount,credit:0,narration:i.description})); state.payments.filter(p=>p.studentId===sid&&p.status==='Posted').forEach(p=>rows.push({date:p.date,ref:p.number,type:'Receipt',debit:0,credit:p.amount,narration:`Bank ${bankName(p.bankId)}`})); state.refunds.filter(r=>r.studentId===sid&&r.status==='Paid').forEach(r=>rows.push({date:r.date,ref:r.number,type:'Refund',debit:r.amount,credit:0,narration:`Refund via ${bankName(r.bankId)}`})); return rows.sort((a,b)=>new Date(a.date)-new Date(b.date)); }
function studentOutstanding(sid){ const bal = sum(studentLedgerRows(sid).map(r=>Number(r.debit)-Number(r.credit))); return bal>0?bal:0; }
function studentCredit(sid){ const bal = sum(studentLedgerRows(sid).map(r=>Number(r.credit)-Number(r.debit))); return bal>0?bal:0; }
function receiptsAgainstInvoice(invId){ return sum(state.payments.filter(p=>p.invoiceId===invId&&p.status==='Posted').map(p=>p.amount)); }
function invoiceOpenBalance(invId){ const inv=findById(state.invoices,invId); return inv&&inv.status==='Posted'?Math.max(0,Number(inv.amount)-receiptsAgainstInvoice(invId)):0; }
function bankBalance(bankId){ const inAmt=sum(state.payments.filter(p=>p.bankId===bankId&&p.status==='Posted').map(p=>p.amount)); const outAmt=sum(state.refunds.filter(r=>r.bankId===bankId&&r.status==='Paid').map(r=>r.amount)); return inAmt-outAmt; }
function invoiceActionHtml(i){ return i.status==='Draft'?`<button class="table-btn primary" onclick="postInvoice('${i.id}')">Post</button>`:i.status==='Posted'?`<button class="table-btn danger" onclick="reverseInvoice('${i.id}')">Reverse</button>`:'-'; }
function receiptActionHtml(p){ return p.status==='Draft'?`<button class="table-btn primary" onclick="postReceipt('${p.id}')">Post</button>`:p.status==='Posted'?`<button class="table-btn danger" onclick="reverseReceipt('${p.id}')">Reverse</button>`:'-'; }
function refundActionHtml(r){ return r.status==='Draft'?`<button class="table-btn primary" onclick="approveRefund('${r.id}')">Approve</button>`:r.status==='Approved'?`<button class="table-btn primary" onclick="payRefund('${r.id}')">Pay</button>`:r.status==='Paid'?`<button class="table-btn danger" onclick="reverseRefund('${r.id}')">Reverse</button>`:'-'; }
window.editBank=id=>{ const b=findById(state.banks,id); els.bankId.value=b.id; els.bankName.value=b.name; els.bankAccountNo.value=b.accountNo||''; els.bankBranch.value=b.branch||''; els.bankStatus.value=b.status; switchSection('finance'); };

function populateExamSubjects(){ const classId=els.examClassId.value; const subs=state.classSubjects.filter(x=>x.classId===classId); fillSelect(els.examSubjectId,[{id:'',label:'Select subject'}].concat(subs.map(s=>({id:s.subjectId,label:subjectName(s.subjectId)})))); }
function loadMarksClass(){ const classId=els.examClassId.value, assessmentId=els.examAssessmentId.value, subjectId=els.examSubjectId.value; if(!classId||!assessmentId||!subjectId) return toast('Select class, assessment, and subject'); const rows=state.students.filter(s=>s.classId===classId&&s.status==='Active'); const outOf=assessmentOutOf(assessmentId); marksLoadedIds=rows.map(r=>r.id); els.examInfo.textContent=`Class ${classLabel(classId)} | ${assessmentName(assessmentId)} | ${subjectName(subjectId)} | Loaded: ${rows.length}`; els.marksTableBody.innerHTML=rows.length?rows.map(s=>{ const existing=state.results.find(r=>r.date===els.examDate.value&&r.studentId===s.id&&r.assessmentId===assessmentId&&r.subjectId===subjectId); const marks=existing?.marks??''; const grade=marks!==''?gradeFromPercent((Number(marks)/outOf)*100):''; return `<tr><td>${escapeHtml(s.admissionNo)}</td><td>${escapeHtml(s.name)}</td><td><input class="mark-input" data-id="${s.id}" type="number" min="0" max="${outOf}" value="${marks}"></td><td>${outOf}</td><td class="grade-cell" data-id="${s.id}">${grade}</td></tr>`; }).join(''):`<tr><td colspan="5" class="muted">No students in class.</td></tr>`; document.querySelectorAll('.mark-input').forEach(inp=>inp.addEventListener('input',()=>{ const m=Number(inp.value||0); document.querySelector(`.grade-cell[data-id="${inp.dataset.id}"]`).textContent = inp.value===''?'':gradeFromPercent((m/outOf)*100); })); }
function saveMarksBatch(){ if(!requirePrivilege('exams_manage')) return; const date=els.examDate.value, classId=els.examClassId.value, assessmentId=els.examAssessmentId.value, subjectId=els.examSubjectId.value; const outOf=assessmentOutOf(assessmentId); if(!marksLoadedIds.length) return toast('Load class first'); marksLoadedIds.forEach(id=>{ const val=document.querySelector(`.mark-input[data-id="${id}"]`)?.value; if(val==='') return; const marks=Number(val); const percentage=(marks/outOf)*100; const rec={id:uid('RES'),date,classId,studentId:id,assessmentId,subjectId,marks,outOf,grade:gradeFromPercent(percentage),percentage}; const existing=state.results.find(r=>r.date===date&&r.studentId===id&&r.assessmentId===assessmentId&&r.subjectId===subjectId); if(existing) Object.assign(existing,rec); else state.results.push(rec); }); persist('Marks saved'); renderAll(); }
function renderResults(){ els.resultsTableBody.innerHTML=state.results.length?state.results.slice().reverse().map(r=>`<tr><td>${formatDate(r.date)}</td><td>${escapeHtml(classLabel(r.classId))}</td><td>${escapeHtml(studentName(r.studentId))}</td><td>${escapeHtml(assessmentName(r.assessmentId))}</td><td>${escapeHtml(subjectName(r.subjectId))}</td><td>${r.marks}/${r.outOf}</td><td>${escapeHtml(r.grade)}</td></tr>`).join(''):`<tr><td colspan="7" class="muted">No results yet.</td></tr>`; }

let currentReport = {title:'Fee Balance Report', rows:[], columns:[]};
function renderReports(){
  els.reportBalance.textContent=money(sum(state.students.map(s=>studentOutstanding(s.id)))); const avg=state.results.length?sum(state.results.map(r=>r.percentage))/state.results.length:0; els.reportPerformance.textContent=`${avg.toFixed(1)}%`; const today=els.attendanceDate.value||new Date().toISOString().slice(0,10); els.reportAttendance.textContent=state.attendance.filter(a=>a.date===today).length; els.reportMessages.textContent='0';
  els.insightBalances.textContent = state.students.filter(s=>studentOutstanding(s.id)>0).length; els.insightCredits.textContent = state.students.filter(s=>studentCredit(s.id)>0).length; els.insightInvoices.textContent = state.invoices.filter(i=>i.status==='Posted').length; els.insightReceipts.textContent = state.payments.filter(p=>p.status==='Posted').length;
  els.reportBalancesTableBody.innerHTML = state.students.length?state.students.map(s=>`<tr><td>${escapeHtml(s.admissionNo)}</td><td>${escapeHtml(s.name)}</td><td>${escapeHtml(classLabel(s.classId))}</td><td>${money(studentOutstanding(s.id))}</td><td>${money(studentCredit(s.id))}</td></tr>`).join(''):`<tr><td colspan="5" class="muted">No students yet.</td></tr>`;
  const insights=[`Active classes: ${activeClasses().length}`,`Students with credit balances: ${state.students.filter(s=>studentCredit(s.id)>0).length}`,`Students with outstanding balances: ${state.students.filter(s=>studentOutstanding(s.id)>0).length}`,`Results entered: ${state.results.length}`,`Attendance records: ${state.attendance.length}`,`Staff records: ${state.staff.length}`,`Banks configured: ${state.banks.length}`]; els.reportInsightList.innerHTML=insights.map(t=>`<div class="list-item">${escapeHtml(t)}</div>`).join('');
  if(!currentReport.rows.length) runReport();
}
function reportFilters(){ return {type:els.reportType.value,classId:els.reportClassId.value,studentId:els.reportStudentId.value,term:(els.reportTerm.value||'').trim(),from:els.reportFromDate.value,to:els.reportToDate.value}; }
function withinDate(d,from,to){ if(!d) return true; const t=new Date(d).getTime(); return (!from || t>=new Date(from).getTime()) && (!to || t<=new Date(to).getTime()); }
function runReport(){
  const f = reportFilters(); let rows=[], columns=[], title='Report';
  if(f.type==='balances'){ title='Fee Balance Report'; columns=['Admission No','Name','Class','Balance','Credit']; rows=state.students.filter(s=>(!f.classId||s.classId===f.classId)&&(!f.studentId||s.id===f.studentId)).map(s=>[s.admissionNo,s.name,classLabel(s.classId),money(studentOutstanding(s.id)),money(studentCredit(s.id))]); }
  else if(f.type==='collections'){ title='Collections Report'; columns=['Date','Receipt No','Student','Class','Bank','Amount','Invoice']; rows=state.payments.filter(p=>p.status==='Posted'&&(!f.classId||findById(state.students,p.studentId)?.classId===f.classId)&&(!f.studentId||p.studentId===f.studentId)&&withinDate(p.date,f.from,f.to)).map(p=>[formatDate(p.date),p.number,studentName(p.studentId),classLabel(findById(state.students,p.studentId)?.classId),bankName(p.bankId),money(p.amount),findById(state.invoices,p.invoiceId)?.number||'']); }
  else if(f.type==='attendance'){ title='Attendance Summary'; columns=['Date','Class','Student','Status']; rows=state.attendance.filter(a=>(!f.classId||a.classId===f.classId)&&(!f.studentId||a.studentId===f.studentId)&&withinDate(a.date,f.from,f.to)).map(a=>[formatDate(a.date),classLabel(a.classId),studentName(a.studentId),a.status]); }
  else if(f.type==='performance'){ title='Class Performance'; columns=['Date','Class','Student','Assessment','Subject','Marks','Grade','%']; rows=state.results.filter(r=>(!f.classId||r.classId===f.classId)&&(!f.studentId||r.studentId===f.studentId)&&withinDate(r.date,f.from,f.to)).map(r=>[formatDate(r.date),classLabel(r.classId),studentName(r.studentId),assessmentName(r.assessmentId),subjectName(r.subjectId),`${r.marks}/${r.outOf}`,r.grade,`${Number(r.percentage||0).toFixed(1)}%`]); }
  else if(f.type==='ledger'){ title='Student Ledger'; const sid=f.studentId||state.students[0]?.id||''; columns=['Date','Reference','Type','Debit','Credit','Running Balance','Narration']; let bal=0; rows=studentLedgerRows(sid).filter(r=>withinDate(r.date,f.from,f.to)).map(r=>{ bal+=Number(r.debit||0)-Number(r.credit||0); return [formatDate(r.date),r.ref,r.type,money(r.debit),money(r.credit),money(bal),r.narration]; }); }
  else if(f.type==='reportcards'){ title='Report Card Summary'; columns=['Student','Class','Subject Entries','Average %','Mean Grade']; const students=(f.classId?state.students.filter(s=>s.classId===f.classId):state.students).filter(s=>!f.studentId||s.id===f.studentId); rows=students.map(s=>{ const rs=state.results.filter(r=>r.studentId===s.id&&withinDate(r.date,f.from,f.to)); const avg=rs.length?sum(rs.map(r=>r.percentage))/rs.length:0; return [s.name,classLabel(s.classId),rs.length,`${avg.toFixed(1)}%`,gradeFromPercent(avg)]; }); }
  else if(f.type==='staff'){ title='Staff Register'; columns=['Staff No','Name','Role','Department','Status']; rows=state.staff.map(s=>[s.staffNo,s.name,s.role,s.department||'',s.status]); }
  else if(f.type==='audit'){ title='Audit Trail'; columns=['Time','Title','Detail']; rows=state.activities.map(a=>[formatDateTime(a.time),a.title,a.detail]); }
  currentReport={title,columns,rows};
  renderReportPreview();
}
function renderReportPreview(){
  els.reportPreviewTitle.textContent=currentReport.title; els.reportPreviewMeta.textContent=`${currentReport.rows.length} row(s) ready for preview/export.`;
  els.reportPreviewHead.innerHTML=currentReport.columns.length?`<tr>${currentReport.columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr>`:'';
  els.reportPreviewBody.innerHTML=currentReport.rows.length?currentReport.rows.map(r=>`<tr>${r.map(v=>`<td>${escapeHtml(String(v))}</td>`).join('')}</tr>`).join(''):`<tr><td class="muted">No matching records.</td></tr>`;
}
function exportCurrentReport(format){ if(!currentReport.rows.length) runReport(); const rows=[currentReport.columns].concat(currentReport.rows);
  if(format==='json'){ return downloadBlob(JSON.stringify({title:currentReport.title,rows:currentReport.rows},null,2), `${slugify(currentReport.title)}.json`, 'application/json'); }
  if(format==='excel'){ const html=`<table><tr>${currentReport.columns.map(c=>`<th>${c}</th>`).join('')}</tr>${currentReport.rows.map(r=>`<tr>${r.map(v=>`<td>${String(v)}</td>`).join('')}</tr>`).join('')}</table>`; return downloadBlob(html, `${slugify(currentReport.title)}.xls`, 'application/vnd.ms-excel'); }
  const csv = rows.map(r=>r.map(v=>`\"${String(v).replaceAll('\"','\"\"')}\"`).join(',')).join('\n'); downloadBlob(csv, `${slugify(currentReport.title)}.csv`, 'text/csv');
}
function printCurrentReport(){ if(!currentReport.rows.length) runReport(); const w=window.open('','_blank'); const table=`<table border="1" cellspacing="0" cellpadding="6" style="width:100%;border-collapse:collapse;font-family:Arial,sans-serif"><thead><tr>${currentReport.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${currentReport.rows.map(r=>`<tr>${r.map(v=>`<td>${String(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; w.document.write(`<html><head><title>${currentReport.title}</title></head><body><h2>${state.settings.schoolName}</h2><h3>${currentReport.title}</h3><p>${els.currentTerm.value||state.settings.currentTerm}</p>${table}</body></html>`); w.document.close(); w.focus(); w.print(); }
function downloadBlob(content,name,type){ const blob=new Blob([content],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href);} 
function slugify(v){ return String(v).toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''); }
function autoGenerateClassInvoices(){ if(!requirePrivilege('finance_manage')) return; const classId = els.reportClassId.value || state.classes[0]?.id; if(!classId) return toast('Create a class first'); const fee=state.feeStructures.find(f=>f.classId===classId); const students=state.students.filter(s=>s.classId===classId && s.status==='Active'); if(!fee) return toast('Set fee structure for selected class first'); if(!students.length) return toast('No active students in selected class'); let count=0; students.forEach(s=>{ const exists=state.invoices.some(i=>i.studentId===s.id && i.term===fee.term && i.description.includes(fee.name) && i.status!=='Reversed'); if(!exists){ state.invoices.push({id:uid('INV'),number:autoNo('INV',state.invoices.length+1),date:new Date().toISOString().slice(0,10),studentId:s.id,term:fee.term,amount:Number(fee.amount),description:`${fee.name} - ${classLabel(classId)}`,status:'Draft'}); count++; } }); logActivity('Auto invoice generation', `${count} draft invoices prepared for ${classLabel(classId)}`); persist(`${count} draft invoices generated`); switchSection('finance'); renderAll(); }
function showTodayReceipts(){ switchSection('reports'); els.reportType.value='collections'; els.reportFromDate.value=new Date().toISOString().slice(0,10); els.reportToDate.value=new Date().toISOString().slice(0,10); runReport(); }


function fillStaticRoleOptions(){ fillSelect(els.userRole, Object.keys(ROLE_PRESETS).map(r=>({id:r,label:r}))); }
function renderPrivilegeMatrix(selected=[]){ els.userPrivilegesGrid.innerHTML = PRIVILEGES.map(([key,label])=>`<label class="priv-item"><input type="checkbox" value="${key}" ${selected.includes('*')||selected.includes(key)?'checked':''}> ${escapeHtml(label)}</label>`).join(''); }
function onRoleChange(){ const role=els.userRole.value; renderPrivilegeMatrix(ROLE_PRESETS[role]||[]); }
function saveUser(e){ e.preventDefault(); if(!requirePrivilege('users_manage')) return; const id=els.userId.value||uid('USR'); const role=els.userRole.value; const privileges=[...els.userPrivilegesGrid.querySelectorAll('input:checked')].map(i=>i.value); upsert(state.auth.users,{id,fullName:els.userFullName.value.trim(),username:els.userUsername.value.trim(),password:els.userPassword.value,role,status:els.userStatus.value,approvalLimit:Number(els.approvalLimit.value||0),privileges:role==='Administrator'?['*']:privileges}); clearForm('user'); persist('User saved'); renderAll(); }
function renderUsers(){ const q=els.userSearch.value?.toLowerCase()||''; const rows=state.auth.users.filter(u=>!q||Object.values(u).join(' ').toLowerCase().includes(q)); els.usersTableBody.innerHTML=rows.length?rows.map(u=>`<tr><td>${escapeHtml(u.fullName)}</td><td>${escapeHtml(u.username)}</td><td>${escapeHtml(u.role)}</td><td>${statusBadge(u.status)}</td><td>${money(u.approvalLimit||0)}</td><td><button class="table-btn" onclick="editUser('${u.id}')">Edit</button></td></tr>`).join(''):`<tr><td colspan="6" class="muted">No users.</td></tr>`; }
window.editUser=id=>{ const u=findById(state.auth.users,id); els.userId.value=u.id; els.userFullName.value=u.fullName; els.userUsername.value=u.username; els.userPassword.value=u.password; els.userRole.value=u.role; els.userStatus.value=u.status; els.approvalLimit.value=u.approvalLimit||0; renderPrivilegeMatrix(u.privileges); switchSection('users'); };

function renderSettings(){ ['schoolName','currentTerm','schoolPhone','schoolEmail','schoolAddress','currency','footerNote'].forEach(k=>els[k].value=state.settings[k]||''); }
function saveSettings(e){ e.preventDefault(); if(!requirePrivilege('settings_manage')) return; ['schoolName','currentTerm','schoolPhone','schoolEmail','schoolAddress','currency','footerNote'].forEach(k=>state.settings[k]=els[k].value); persist('Settings saved'); syncAuthUI(); renderAll(); }

function loadSampleData(){
  closeSidebarOnDesktop();
  if(!confirm('Load sample data? Existing data remains.')) return;
  if(!state.staff.length){ state.staff.push({id:'ST1',staffNo:'T001',name:'Mary Achieng',role:'Teacher',department:'Junior School',phone:'',status:'Active'},{id:'ST2',staffNo:'T002',name:'Peter Otieno',role:'Teacher',department:'Upper School',phone:'',status:'Active'}); }
  if(!state.classes.length){ state.classes.push({id:'C1',name:'Grade 4',stream:'East',teacherId:'ST1',status:'Active'},{id:'C2',name:'Grade 5',stream:'West',teacherId:'ST2',status:'Active'}); }
  if(!state.feeStructures.length){ state.feeStructures.push({id:'F1',classId:'C1',name:'School Fees',term:'Term 1',amount:15000},{id:'F2',classId:'C2',name:'School Fees',term:'Term 1',amount:18000}); }
  if(!state.subjects.length){ state.subjects.push({id:'S1',name:'Mathematics'},{id:'S2',name:'English'},{id:'S3',name:'Science'}); }
  if(!state.classSubjects.length){ state.classSubjects.push({id:'M1',classId:'C1',subjectId:'S1'},{id:'M2',classId:'C1',subjectId:'S2'},{id:'M3',classId:'C2',subjectId:'S1'},{id:'M4',classId:'C2',subjectId:'S3'}); }
  if(!state.assessments.length){ state.assessments.push({id:'A1',name:'CAT 1',outOf:30},{id:'A2',name:'Exam',outOf:70}); }
  if(!state.students.length){ state.students.push({id:'SD1',admissionNo:'ADM001',name:'Brian Ouma',classId:'C1',parent:'Alice Ouma',phone:'',status:'Active',notes:''},{id:'SD2',admissionNo:'ADM002',name:'Faith Atieno',classId:'C1',parent:'Paul Atieno',phone:'',status:'Active',notes:''},{id:'SD3',admissionNo:'ADM003',name:'Mark Onyango',classId:'C2',parent:'Lucy Onyango',phone:'',status:'Active',notes:''}); }
  if(!state.banks.length){ state.banks.push({id:'B1',name:'KCB Fee Collection',accountNo:'123456789',branch:'Bondo',status:'Active'}); }
  persist('Sample data loaded'); renderAll();
}

function exportBackup(){ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='edubill_pro_v10_kenya_primary_top_tier_backup.json'; a.click(); URL.revokeObjectURL(a.href); }
function importBackup(e){ const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ try{ const data=JSON.parse(reader.result); Object.keys(defaultState).forEach(k=>state[k]=data[k]??structuredClone(defaultState[k])); persist('Backup imported'); syncAuthUI(); renderAll(); }catch{ toast('Invalid backup file'); } }; reader.readAsText(file); }

function clearForm(type){ const map={class:['classId','className','classStream','classTeacherId','classStatus'],fee:['feeId','feeClassId','feeName','feeTerm','feeAmount'],subject:['subjectId','subjectName'],assessment:['assessmentId','assessmentName','assessmentOutOf'],student:['studentId','admissionNo','studentName','studentClassId','studentClassTeacher','studentFeeHint','studentParent','studentPhone','studentStatus','studentNotes'],staff:['staffId','staffNo','staffName','staffRole','staffDepartment','staffPhone','staffStatus'],bank:['bankId','bankName','bankAccountNo','bankBranch','bankStatus'],invoice:['invoiceId','invoiceStudentId','invoiceTerm','invoiceAmount','invoiceDescription'],payment:['paymentId','paymentStudentId','paymentInvoiceId','paymentBankId','paymentMethod','paymentAmount'],refund:['refundId','refundStudentId','refundCreditHint','refundBankId','refundAmount','refundReason'],user:['userId','userFullName','userUsername','userPassword','userRole','userStatus','approvalLimit']}; (map[type]||[]).forEach(id=>{ if(els[id]) els[id].value=''; }); if(type==='assessment') els.assessmentOutOf.value=100; if(type==='payment') els.paymentMethod.value='Cash'; if(type==='class' || type==='student' || type==='bank' || type==='staff') { if(els[`${type}Status`]) els[`${type}Status`].value='Active'; } if(type==='user'){ els.userStatus.value='Active'; els.approvalLimit.value=0; fillStaticRoleOptions(); renderPrivilegeMatrix(); } setToday(); updateStudentClassHints(); updateRefundCreditHint(); }
function upsert(arr, rec){ const i=arr.findIndex(x=>x.id===rec.id); if(i>=0) arr[i]={...arr[i],...rec}; else arr.push(rec); }
function findById(arr,id){ return arr.find(x=>x.id===id); }
function optSel(cur,val){ return (cur||'Present')===val?'selected':''; }
function autoNo(prefix,n){ return `${prefix}-${String(n).padStart(4,'0')}`; }
